### ISSUE TITLE
Entrypoint.sh: 5: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by tpkowastaken** [Vacxe/google-play-cli#28]
Hi. I've encountered a bug in 

```
Run vacxe/google-play-cli-kt@master
  with:
    service-account-json: ***
  
    package-name: cz.appelevate.autojidelna
    custom-script: sh scripts/ci/deploy_google_play.sh build/app/outputs/bundle/release/app-release.aab 15 internal completed build/app/outputs/mapping/release/mapping.txt build/symbols.zip
    template: custom-script
    track: internal
  env:
    JAVA_HOME: 
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.13-11/x64
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.[2](https://github.com/App-Elevate/AUT.aplikace/actions/runs/12292569873/job/34303489734?pr=5#step:15:2)2.3-x64
    PUB_CACHE: /home/runner/.pub-cache
    install_path: /home/runner/.config/shorebird
/usr/bin/docker run --name be2a82b54d57ae5b74f2c8692a9b[3](https://github.com/App-Elevate/AUT.aplikace/actions/runs/12292569873/job/34303489734?pr=5#step:15:3)6ace0ed4_df74f5 --label 9be2a8 --workdir /github/workspace --rm -e "JAVA_HOME" -e "JAVA_HOME_17_X6[4](https://github.com/App-Elevate/AUT.aplikace/actions/runs/12292569873/job/34303489734?pr=5#step:15:4)" -e "FLUTTER_ROOT" -e "PUB_CACHE" -e "install_path" -e "INPUT_SERVICE-ACCOUNT-JSON" -e "INPUT_PACKAGE-NAME" -e "INPUT_CUSTOM-SCRIPT" -e "INPUT_TEMPLATE" -e "INPUT_VERSION-CODE" -e "INPUT_TRACK" -e "INPUT_PATH-TO-APK" -e "INPUT_PATH-TO-BUNDLE" -e "INPUT_PATH-TO-MAPPING" -e "INPUT_CHANGES-NOT-SENT-FOR-REVIEW" -e "INPUT_STATUS" -e "INPUT_USER-FRACTION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_EVENT_PATH" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "GITHUB_ACTION" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/_work/_temp/_github_home":"/github/home" -v "/home/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/_work/AUT.aplikace/AUT.aplikace":"/github/workspace" 9be2a8:2b[5](https://github.com/App-Elevate/AUT.aplikace/actions/runs/12292569873/job/34303489734?pr=5#step:15:5)4d57ae5b74f2c8692a9b36ace0ed4  "***
" "custom-script" "sh scripts/ci/deploy_google_play.sh build/app/outputs/bundle/release/app-release.aab 15 internal completed build/app/outputs/mapping/release/mapping.txt build/symbols.zip" "cz.appelevate.autojidelna" "" "internal" "" "" "" "" "" ""
/entrypoint.sh: 5: Syntax error: "(" unexpected
```

custom script:

```bash
#!/bin/bash

set -e

PATH_TO_BUNDLE="${1}"
VERSION_CODE="${2}"
TRACK="${3}"
STATUS="${4}"
PATH_TO_MAPPING="${5}"
PATH_TO_NATIVE_SYMBOLS="${6}"

echo "---"
echo "Path to bundle: $PATH_TO_BUNDLE"
echo "Version code: $VERSION_CODE"
echo "Track: $TRACK"
echo "Status: $STATUS"
echo "Path to mapping: $PATH_TO_MAPPING"
echo "Path to native symbols: $PATH_TO_NATIVE_SYMBOLS"
echo "---"

EDIT_ID=$(google-play-cli edit create)
echo "Edit id created: $EDIT_ID"
echo "Upload Bundle..."
google-play-cli bundles upload --edit-id "$EDIT_ID" --bundle "$PATH_TO_BUNDLE"
echo "Upload deobfuscation files..."
google-play-cli deobfuscation-files upload --edit-id "$EDIT_ID" --deobfuscation "$PATH_TO_MAPPING" --version-code "$VERSION_CODE"
google-play-cli deobfuscation-files upload --edit-id "$EDIT_ID" --deobfuscation "$PATH_TO_NATIVE_SYMBOLS" --version-code "$VERSION_CODE" -t nativeCode
echo "Update track..."
google-play-cli tracks update --edit-id "$EDIT_ID" --version-code "$VERSION_CODE" --track "$TRACK" \
  ${USER_FRACTION:+ --user-fraction "$USER_FRACTION"} \
  ${STATUS:+ --status "$STATUS"}
echo "Validate..."
google-play-cli edit validate --edit-id "$EDIT_ID"
echo "Commit..."
google-play-cli edit commit --edit-id "$EDIT_ID" \
  ${FLAG_CHANGES_NOT_SENT_FOR_REVIEW:+ --changes-not-sent-for-review "$FLAG_CHANGES_NOT_SENT_FOR_REVIEW"}
  ```
I remember that It [worked before](https://github.com/App-Elevate/Autojidelna/actions/runs/11040773940) so it's propably not because of the script.

Could you please direct me to where I should look for an error message? I have no idea how I could affect the dockers entrypoint.sh.

The repository I'm having issues with is [open source](https://github.com/App-Elevate/Autojidelna). Just to warn you a bit of documentation is in czech. Code is however written in english.

This bug was introduced in [v0.4.9](https://github.com/Vacxe/google-play-cli/releases/tag/0.4.9). It works completely ok on 0.4.8
